CREATE DATABASE quizz;

CREATE TABLE questions ( 
	questionID		INT UNSIGNED 	NOT NULL AUTO_INCREMENT,
    questionNearID  INT UNSIGNED    NOT NULL DEFAULT 0,
	question		VARCHAR(1000)	NOT NULL DEFAULT '',
	answer			VARCHAR(500)	NOT NULL DEFAULT '',
    knowledge		VARCHAR(20)		NOT NULL DEFAULT '',
	theme			INT UNSIGNED	NOT NULL DEFAULT 0,
    questionMaker	INT UNSIGNED	NOT NULL DEFAULT '',
	PRIMARY KEY (questionID),
    FOREIGN KEY (questionMaker) REFERENCES users (userID),
    FOREIGN KEY (theme) REFERENCES theme (ID)
	);
    
CREATE TABLE answers (
	ID				INT UNSIGNED	NOT NULL AUTO_INCREMENT,
    question		INT UNSIGNED	NOT NULL DEFAULT 0,
    answer			VARCHAR(500)	NOT NULL DEFAULT '',
    PRIMARY KEY (ID),
    FOREIGN KEY (question) REFERENCES questions (questionNearID)
    );

CREATE TABLE theme (
	ID				INT UNSIGNED	NOT NULL AUTO_INCREMENT,
    label			VARCHAR(50)		NOT NULL DEFAULT '',
    parent			INT UNSIGNED	DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE users (
	userID			INT UNSIGNED	NOT NULL AUTO_INCREMENT,
    telegramID		INT UNSIGNED	NOT NULL DEFAULT 0,
    PRIMARY KEY (userID)
    );
ALTER TABLE users ADD UNIQUE (telegramID);

CREATE TABLE knowledge (
	ID				INT UNSIGNED	NOT NULL AUTO_INCREMENT,
	user			INT UNSIGNED	NOT NULL DEFAULT '',
    knowledge		VARCHAR(15)		NOT NULL DEFAULT '',
    theme			INT UNSIGNED	NOT NULL DEFAULT 0,
    PRIMARY KEY(ID),
    FOREIGN KEY (user) REFERENCES users (userID)
);

CREATE TABLE resources(
	resourceID		INT UNSIGNED	NOT NULL AUTO_INCREMENT,
    resourceSite	VARCHAR(500)	NOT NULL DEFAULT '',
    theme			INT UNSIGNED	NOT NULL DEFAULT 0,
    knowledge		VARCHAR(50)		NOT NULL DEFAULT '',
    PRIMARY KEY(resourceID)
    );
    
