CREATE DATABASE quizz;

CREATE TABLE questions ( 
	questionID	INT UNSIGNED 	NOT NULL AUTO_INCREMENT,
	question	VARCHAR(1000)	NOT NULL DEFAULT '',
	answer		VARCHAR(500)	NOT NULL DEFAULT '',
	theme		VARCHAR(50)	NOT NULL DEFAULT '',
	PRIMARY KEY (questionID)
	);
