from DBInterface import *

# Create objects
#Check API for creation, almost all parameters unnecessary
print 'Users :'
print DBInterace.CreateUser(1, u'Vasya', u'Pupkin').firstname
print DBInterace.CreateUser(2, u'Vadim', u'Kirilin').firstname

# Use s_CreateTheme instead of CreateTheme, s_ - safe method
# It will allow you to avoid dpulicates in database, such as two themes with tag "Math" and same parents but with different ids
print 'Themes :'
biology_theme = DBInterace.s_CreateTheme(label='Biology', parent=0)
print 'Theme created, label :', biology_theme.label
geography_theme = DBInterace.s_CreateTheme(label='Geography', parent=0)
print 'Theme created, label :', geography_theme.label
biology_mammals = DBInterace.s_CreateTheme(label='Mammals', parent=biology_theme.id)
print 'Theme Biology-Mammals created, label :', biology_mammals.label
geography_mammals = DBInterace.s_CreateTheme(label='Mammals', parent=geography_theme.id)
print 'Theme Geography-Mammals created, label :', geography_mammals.label
geography_mammals = DBInterace.s_CreateTheme(label='Arts',  parent=0)
geography_mammals = DBInterace.s_CreateTheme(label='Enterteinment',  parent=0)
geography_mammals = DBInterace.s_CreateTheme(label='History',  parent=0)
geography_mammals = DBInterace.s_CreateTheme(label='Science & Technology',  parent=0)
geography_mammals = DBInterace.s_CreateTheme(label='Sports',  parent=0)

# Use s_CreateDifficulty instead of CreateDifficulty, s_ - safe method
# It will allow you to avoid dpulicates in database, such as two difficulties with tag "Hard" but with different ids
print 'Difficulties :'
print DBInterace.s_CreateDifficulty(difficulty='Easy').difficulty
print DBInterace.s_CreateDifficulty(difficulty='Medium').difficulty
print DBInterace.s_CreateDifficulty(difficulty='Hard').difficulty


question1= DBInterace.s_CreateQuestion(text="What is the location of London\'s National Gallery?",difficulty=3,theme=5,creator=1)
question2= DBInterace.s_CreateQuestion(text="What nationality was Edvard Munch, who produced the famous painting The Scream in 1893?",difficulty=2,theme=5,creator=1)
question3= DBInterace.s_CreateQuestion(text="Pablo Picasso was born in 1881 in which Spanish city?",difficulty=2,theme=5,creator=1)
question4= DBInterace.s_CreateQuestion(text="Which Dutch artist painted the Laughing Cavalier in 1624?",difficulty=1,theme=5,creator=1)
question5= DBInterace.s_CreateQuestion(text="Which English artist painted Rain, Steam and Speed - The Great Western Railway in 1844?",difficulty=1,theme=5,creator=1)
question6= DBInterace.s_CreateQuestion(text="What is the colloquial name for the 1871 painting Arrangement in Grey and Black: The Artist\'s Mother?",difficulty=1,theme=5,creator=1)
question7= DBInterace.s_CreateQuestion(text="Between 1887 and 1888 Vincent van Gogh produced a series of still life paintings depicting which flowers?",difficulty=2,theme=5,creator=1)
question8= DBInterace.s_CreateQuestion(text="The English artist George Stubbs, who died in 1806, is best remembered for his paintings of what?",difficulty=2,theme=5,creator=1)
question9= DBInterace.s_CreateQuestion(text="Who created the modern sculpture Angel of the North, that overlooks the A1 road and the East Coast main line in Gateshead?",difficulty=1,theme=5,creator=1)
question10= DBInterace.s_CreateQuestion(text="Hans Holbein the Younger was criticized by Henry VIII for painting a flattering portrait of whom?",difficulty=2,theme=5,creator=1)
question11= DBInterace.s_CreateQuestion(text="What spoiled Becky and Steve\'s wedding reception in Coronation Street last week?",difficulty=2,theme=6,creator=1)
question12= DBInterace.s_CreateQuestion(text="The BBC announced last week that which former presenter has set up his own version of the Blue Peter garden in Edinburgh?",difficulty=1,theme=6,creator=1)
question13= DBInterace.s_CreateQuestion(text="Who plays the title role in the film The Time Traveler\'s Wife, released last Friday?",difficulty=3,theme=6,creator=1)
question14= DBInterace.s_CreateQuestion(text="Which celebrity signed a 1.5 million deal last week to publish a cookbook?",difficulty=2,theme=6,creator=1)
question15= DBInterace.s_CreateQuestion(text="What is the title of Beyonce\'s latest single, that reached No 5 in the charts last week?",difficulty=3,theme=6,creator=1)
question16= DBInterace.s_CreateQuestion(text="The new Quentin Tarantino film Inglourious Basterds, due for release on Friday, is set during which war?",difficulty=2,theme=6,creator=1)
question17= DBInterace.s_CreateQuestion(text="Which rock band last week released a 20th anniversary edition of their debut album?",difficulty=2,theme=6,creator=1)
question18= DBInterace.s_CreateQuestion(text="The BBC announced last week that which Radio 1 DJ is to leave the station due to a scheduling shake-up?",difficulty=2,theme=6,creator=1)
question19= DBInterace.s_CreateQuestion(text="Which EastEnders character last week followed his lady- love Brenda as she emigrated to Madeira?",difficulty=1,theme=6,creator=1)
question20= DBInterace.s_CreateQuestion(text="What is the real name of the Big Brother housemate Halfwit, who was evicted from the show last week?",difficulty=3,theme=6,creator=1)
question21= DBInterace.s_CreateQuestion(text="Which German city lies farthest south - Dortmund, Duisburg, Essen or Leipzig?",difficulty=2,theme=2,creator=1)
question22= DBInterace.s_CreateQuestion(text="Of Greece\'s 2000 islands, how many are inhabited?",difficulty=3,theme=2,creator=1)
question23= DBInterace.s_CreateQuestion(text="What is the administrative centre of County Kildare in Ireland?",difficulty=1,theme=2,creator=1)
question24= DBInterace.s_CreateQuestion(text="Near which Italian city is Frascati wine produced?",difficulty=1,theme=2,creator=1)
question25= DBInterace.s_CreateQuestion(text="In which country is Lake Balaton?",difficulty=1,theme=2,creator=1)
question26= DBInterace.s_CreateQuestion(text="Which Spanish city contains the Alcazar, whose construction began in 1531?",difficulty=3,theme=2,creator=1)
question27= DBInterace.s_CreateQuestion(text="Famous for its local cheese, near which city is Roquefort located?",difficulty=3,theme=2,creator=1)
question28= DBInterace.s_CreateQuestion(text="Of which sport is \"pesapallo\" a local Finnish variation?",difficulty=3,theme=2,creator=1)
question29= DBInterace.s_CreateQuestion(text="Which European country was ruled until 1985 by Enver Hoxha?",difficulty=2,theme=2,creator=1)
question30= DBInterace.s_CreateQuestion(text="Which has the largest population - Bremen, Lille, Ljubljana or Reykjavik?",difficulty=3,theme=2,creator=1)
question31= DBInterace.s_CreateQuestion(text="Approximately how many men did the British lose at the Battle of Jutland in 1916?",difficulty=1,theme=7,creator=1)
question32= DBInterace.s_CreateQuestion(text="In which year did Chaucer complete \"The Canterbury Tales\"?",difficulty=3,theme=7,creator=1)
question33= DBInterace.s_CreateQuestion(text="Of which independent state did Kwame Nkrumah become the first Prime Minister?",difficulty=2,theme=7,creator=1)
question34= DBInterace.s_CreateQuestion(text="In which year was Marie-Antoinette executed?",difficulty=1,theme=7,creator=1)
question35= DBInterace.s_CreateQuestion(text="Where did the Venetian merchant and adventurer Marco Polo die?",difficulty=2,theme=7,creator=1)
question36= DBInterace.s_CreateQuestion(text="In which year did the Middle East\'s \"Six Day War\" take place?",difficulty=1,theme=7,creator=1)
question37= DBInterace.s_CreateQuestion(text="Against which country did Russia wage war in 1904-05?",difficulty=3,theme=7,creator=1)
question38= DBInterace.s_CreateQuestion(text="Founded in 1746, which is the fourth-oldest university in the USA?",difficulty=2,theme=7,creator=1)
question39= DBInterace.s_CreateQuestion(text="During the reign of Gustav IV, which country lost the territory of Finland in 1808?",difficulty=2,theme=7,creator=1)
question40= DBInterace.s_CreateQuestion(text="In which country did the South American freedom fighter Simon Bolivar die in 1830?",difficulty=1,theme=7,creator=1)
question41= DBInterace.s_CreateQuestion(text="Who co-founded the Apple Corporation with Steve Wozniak in 1976?",difficulty=3,theme=8,creator=1)
question42= DBInterace.s_CreateQuestion(text="What do the initials stand for in the name of the US television network PBS?",difficulty=1,theme=8,creator=1)
question43= DBInterace.s_CreateQuestion(text="In September 1961 Border Television began transmitting from where?",difficulty=1,theme=8,creator=1)
question44= DBInterace.s_CreateQuestion(text="In 1792 the French inventor Claude Chappe built the world\'s first practical semaphore system between Paris and which other city?",difficulty=3,theme=8,creator=1)
question45= DBInterace.s_CreateQuestion(text="In which US state are the headquarters of the Microsoft Corporation?",difficulty=2,theme=8,creator=1)
question46= DBInterace.s_CreateQuestion(text="When ITV began broadcasting in 1955, what was the first product to be advertised?",difficulty=1,theme=8,creator=1)
question47= DBInterace.s_CreateQuestion(text="Which comedian made the UK\'s first mobile phone call on I January 1985?",difficulty=1,theme=8,creator=1)
question48= DBInterace.s_CreateQuestion(text="Which piece of computer hardware was invented by Douglas Engelbart in the USA in 1964?",difficulty=2,theme=8,creator=1)
question49= DBInterace.s_CreateQuestion(text="What stopped BBC from broadcasting on its intended launch date of 20 April 1964?",difficulty=3,theme=8,creator=1)
question50= DBInterace.s_CreateQuestion(text="Which offshore radio station began broadcasting on Easter Sunday 1965?",difficulty=2,theme=8,creator=1)
question51= DBInterace.s_CreateQuestion(text="Former England football manager Bobby Robson, who died last week, was born in which County Durham mining village?",difficulty=3,theme=9,creator=1)
question52= DBInterace.s_CreateQuestion(text="Edgbaston, the venue for this year\'s third Ashes test, is the home of which cricketing county?",difficulty=2,theme=9,creator=1)
question53= DBInterace.s_CreateQuestion(text="Which US TV network is to broadcast live Premier League games this coming season, following the collapse of Setanta?",difficulty=3,theme=9,creator=1)
question54= DBInterace.s_CreateQuestion(text="Which golf course staged this year\'s British Women\'s Open?",difficulty=1,theme=9,creator=1)
question55= DBInterace.s_CreateQuestion(text="Spurs beat Hull City last week in the final of the Asia Cup, in which city?",difficulty=2,theme=9,creator=1)
question56= DBInterace.s_CreateQuestion(text="What is the name of the contract recently signed by the FIA and the Formula One Teams' Association?",difficulty=2,theme=9,creator=1)
question57= DBInterace.s_CreateQuestion(text="Which 2009 Tour de France stage winner was suspended last week after testing positive for the blood-booster EPO?",difficulty=3,theme=9,creator=1)
question58= DBInterace.s_CreateQuestion(text="The 2013 Rugby League World Cup, recently awarded to Britain, will be contested by how many teams?",difficulty=1,theme=9,creator=1)
question59= DBInterace.s_CreateQuestion(text="Serena Williams was knocked out of the Bank of the West tennis tournament in Stanford, California last week by Samantha Stosur",difficulty=3,theme=9,creator=1)
question60= DBInterace.s_CreateQuestion(text="The Goodwood Cup was won last Thursday by Schiaparelli. Who was the winning jockey?",difficulty=3,theme=9,creator=1)
question61= DBInterace.s_CreateQuestion(text=u'What is the Macintosh computer named after?',difficulty=2,theme=8,creator=1)
question62= DBInterace.s_CreateQuestion(text=u'Under what name is the Chinese gooseberry normally sold?',difficulty=2,theme=8,creator=1)
question63= DBInterace.s_CreateQuestion(text=u'How much does a cubic metre of water weigh?',difficulty=2,theme=8,creator=1)
question64= DBInterace.s_CreateQuestion(text=u'How many square metres in a hectare?',difficulty=2,theme=8,creator=1)
question65= DBInterace.s_CreateQuestion(text=u'On which planet is the tallest mountain in the Solar System?',difficulty=2,theme=8,creator=1)
question66= DBInterace.s_CreateQuestion(text=u'Which is the largest species of dolphin?',difficulty=2,theme=8,creator=1)
question67= DBInterace.s_CreateQuestion(text=u'Which planet of the solar system has its 27 moons named after characters from the works of William Shakespeare and Alexander Pope?',difficulty=2,theme=8,creator=1)
question68= DBInterace.s_CreateQuestion(text=u'What is the SI unit of temperature?',difficulty=2,theme=8,creator=1)
question69= DBInterace.s_CreateQuestion(text=u'LSD is a synthetic derivative of which type of naturally occurring growth?',difficulty=2,theme=8,creator=1)
question70= DBInterace.s_CreateQuestion(text=u'On the Mohs scale of hardness, what is the second hardest mineral, after diamond?',difficulty=2,theme=8,creator=1)
question71= DBInterace.s_CreateQuestion(text=u'In biology, what is symbiosis?',difficulty=2,theme=8,creator=1)
question72= DBInterace.s_CreateQuestion(text=u'Who flew in Vostok 1?',difficulty=2,theme=8,creator=1)
question73= DBInterace.s_CreateQuestion(text=u'What\'s the name given to lines of equal underwater depth on maps?',difficulty=2,theme=8,creator=1)
question74= DBInterace.s_CreateQuestion(text=u'The X-Men character Wolverine is named after the animal of the same name. What kind of animal is a wolverine?',difficulty=2,theme=8,creator=1)
question75= DBInterace.s_CreateQuestion(text=u'What is the SI unit of frequency (used in measuring audio and radio transmissions among many others)?',difficulty=2,theme=8,creator=1)
question76= DBInterace.s_CreateQuestion(text=u'What is the name of a single dot on a computer monitor screen?',difficulty=2,theme=8,creator=1)
question77= DBInterace.s_CreateQuestion(text=u'Where would you commonly find a sand dollar?',difficulty=2,theme=8,creator=1)
question78= DBInterace.s_CreateQuestion(text=u'Which gas has the chemical formula CO?',difficulty=2,theme=8,creator=1)
question79= DBInterace.s_CreateQuestion(text=u'What was the Wright Brother\'s first successful aeroplane called?',difficulty=2,theme=8,creator=1)
question80= DBInterace.s_CreateQuestion(text=u'What is the name of the study of the motion of the earth\'s crust?',difficulty=2,theme=8,creator=1)
question81= DBInterace.s_CreateQuestion(text=u'Graphite is composed of which element?',difficulty=2,theme=8,creator=1)
question82= DBInterace.s_CreateQuestion(text=u'What medical condition gets its name from the Greek "half a head"?',difficulty=2,theme=8,creator=1)
question83= DBInterace.s_CreateQuestion(text=u'Which isotope is commonly used to date decayed organic matter?',difficulty=2,theme=8,creator=1)
question84= DBInterace.s_CreateQuestion(text=u'Do astronauts have mass in outer space?',difficulty=2,theme=8,creator=1)
question85= DBInterace.s_CreateQuestion(text=u'Which is the hardest tissue in men, as well as in women?',difficulty=2,theme=8,creator=1)
question86= DBInterace.s_CreateQuestion(text=u'On the moon, what colour is the sky?',difficulty=2,theme=8,creator=1)
question87= DBInterace.s_CreateQuestion(text=u'What did Tim Berners-Lee create and where?',difficulty=2,theme=8,creator=1)
question88= DBInterace.s_CreateQuestion(text=u'The detrimental effects of DHMO (di-hydrogen monoxide) were spelled out in the early 90s. What is dihydrogen monoxide?',difficulty=2,theme=8,creator=1)
question89= DBInterace.s_CreateQuestion(text=u'Boats and planes roll when rotating about their longitudinal axis. What are the other two rotations called?',difficulty=2,theme=8,creator=1)
question90= DBInterace.s_CreateQuestion(text=u'The Indian-Pacific train links the two oceans. Between which two cities does it run?',difficulty=2,theme=8,creator=1)
question91= DBInterace.s_CreateQuestion(text=u'If, in Japan, you were travelling on a Shinkansen, what mode of transport would you be using?',difficulty=2,theme=8,creator=1)
question92= DBInterace.s_CreateQuestion(text=u'What in Asia is a Tuk-tuk?',difficulty=2,theme=8,creator=1)
question93= DBInterace.s_CreateQuestion(text=u'What is the SI unit of force?',difficulty=2,theme=8,creator=1)
question94= DBInterace.s_CreateQuestion(text=u'What lies above the troposphere?',difficulty=2,theme=8,creator=1)
question95= DBInterace.s_CreateQuestion(text=u'What is the name of the shortest route between two points on a sphere? (Such as flying between two points on earth.)',difficulty=2,theme=8,creator=1)
question96= DBInterace.s_CreateQuestion(text=u'Alec Issigonis designed one of the most famous cars of the 20th century. Which one?',difficulty=2,theme=8,creator=1)
question97= DBInterace.s_CreateQuestion(text=u'Which is the most powerful rocket used operationally?',difficulty=2,theme=8,creator=1)
question98= DBInterace.s_CreateQuestion(text=u'What in radio does AM stand for?',difficulty=2,theme=8,creator=1)
question99= DBInterace.s_CreateQuestion(text=u'In the physical world (as opposed to art) what are the primary colours?',difficulty=2,theme=8,creator=1)
question100= DBInterace.s_CreateQuestion(text=u'Solid carbon dioxide is known by what name?',difficulty=2,theme=8,creator=1)
question101= DBInterace.s_CreateQuestion(text=u'What extinct creature got its name from the Portuguese word for stupid?',difficulty=2,theme=8,creator=1)
question102= DBInterace.s_CreateQuestion(text=u'What is the angle between the hands of a clock at 1 o\'clock?',difficulty=2,theme=8,creator=1)
question103= DBInterace.s_CreateQuestion(text=u'What is the chemical symbol for Ozone?',difficulty=2,theme=8,creator=1)
question104= DBInterace.s_CreateQuestion(text=u'What is the name of the mascot on the bonnet of a Rolls Royce?',difficulty=2,theme=8,creator=1)
question105= DBInterace.s_CreateQuestion(text=u'What is the three-dimensional image created with laser beams called?',difficulty=2,theme=8,creator=1)
question106= DBInterace.s_CreateQuestion(text=u'What type of animal are Belugas?',difficulty=2,theme=8,creator=1)
question107= DBInterace.s_CreateQuestion(text=u'What were (and still are)\'Skyscrapers\' before the term was applied to tall buildings?',difficulty=2,theme=8,creator=1)
question108= DBInterace.s_CreateQuestion(text=u'What would you use Archimede\'s Screw for?',difficulty=2,theme=8,creator=1)
question109= DBInterace.s_CreateQuestion(text=u'Whats the the name for the bending of light as it passes from one medium to another?',difficulty=2,theme=8,creator=1)
question110= DBInterace.s_CreateQuestion(text=u'Where is the hypocentre of an earthquake in relation to its epicentre?',difficulty=2,theme=8,creator=1)
question111= DBInterace.s_CreateQuestion(text=u'Which is the only muscle in your body that is only attached at one end?',difficulty=2,theme=8,creator=1)
question112= DBInterace.s_CreateQuestion(text=u'Which planet in our solar system has an orbital period of 687 days?',difficulty=2,theme=8,creator=1)
question113= DBInterace.s_CreateQuestion(text=u'Who discovered that all objects, heavy or light, fall at the same velocity?',difficulty=2,theme=8,creator=1)
question114= DBInterace.s_CreateQuestion(text=u'What shape is the DNA molecule?',difficulty=2,theme=8,creator=1)
question115= DBInterace.s_CreateQuestion(text=u'BASIC, Perl, and Python are types of what?',difficulty=2,theme=8,creator=1)
question116= DBInterace.s_CreateQuestion(text=u'By what name is "Jerry\'s Guide to the World Wide Web" now known?',difficulty=2,theme=8,creator=1)
question117= DBInterace.s_CreateQuestion(text=u'Disgusting-sounding ailments no.1: What is Borborygmus?',difficulty=2,theme=8,creator=1)
question118= DBInterace.s_CreateQuestion(text=u'Evaporation is changing from a liquid to gas. What is changing from a solid to a gas called?',difficulty=2,theme=8,creator=1)
question119= DBInterace.s_CreateQuestion(text=u'How many astronauts crewed the Gemini series of spacecraft?',difficulty=2,theme=8,creator=1)
question120= DBInterace.s_CreateQuestion(text=u'How many astronauts crewed the Mercury series of spacecraft?',difficulty=2,theme=8,creator=1)
question121= DBInterace.s_CreateQuestion(text=u'If 8 bits make a byte, what do 4 bits constitute?',difficulty=2,theme=8,creator=1)
question122= DBInterace.s_CreateQuestion(text=u'In photography, what does SLR stand for?',difficulty=2,theme=8,creator=1)
question123= DBInterace.s_CreateQuestion(text=u'In which US state did the Wright brothers first fly?',difficulty=2,theme=8,creator=1)
question124= DBInterace.s_CreateQuestion(text=u'Litmus paper turns what colour when in contact with an acid?',difficulty=2,theme=8,creator=1)
question125= DBInterace.s_CreateQuestion(text=u'Many of us use CDROMs these days, but what does the acronym mean?',difficulty=2,theme=8,creator=1)
question126= DBInterace.s_CreateQuestion(text=u'Mrs. Thomas Smith of Ryde, NSW, Australia, produced a new variety of fruit in 1868. What is it called?',difficulty=2,theme=8,creator=1)
question127= DBInterace.s_CreateQuestion(text=u'On the Moh Hardness scale, what has a hardness of 10?',difficulty=2,theme=8,creator=1)
question128= DBInterace.s_CreateQuestion(text=u'Referring to internet connections, what does ADSL mean?',difficulty=2,theme=8,creator=1)
question129= DBInterace.s_CreateQuestion(text=u'The prefix mega- is a millionfold in the SI units and giga is a billion. Tera is a trillion but what is the quadrillionfold (10 to the power of 15) prefix?',difficulty=2,theme=8,creator=1)
question130= DBInterace.s_CreateQuestion(text=u'The winter solstice (summer in the Southern hemisphere) occurs when the sun is furthest from the equator (on December 22nd). What do we call the days the sun crosses the equator in March and September?',difficulty=2,theme=8,creator=1)
question131= DBInterace.s_CreateQuestion(text=u'To the nearest whole number, how many revolutions does the moon make around the earth in a',difficulty=2,theme=8,creator=1)
question132= DBInterace.s_CreateQuestion(text=u'Strange, charm, up, down, top, and bottom are types of what?',difficulty=2,theme=8,creator=1)
question133= DBInterace.s_CreateQuestion(text=u'What are the two types of camel called?',difficulty=2,theme=8,creator=1)
question134= DBInterace.s_CreateQuestion(text=u'What colour is caffeine?',difficulty=2,theme=8,creator=1)
question135= DBInterace.s_CreateQuestion(text=u'What colour is the\'Black Box\' found in commercial planes?',difficulty=2,theme=8,creator=1)
question136= DBInterace.s_CreateQuestion(text=u'What did Einstein get the Nobel prize for?',difficulty=2,theme=8,creator=1)
question137= DBInterace.s_CreateQuestion(text=u'What did John Logie Baird invent in 1925?',difficulty=2,theme=8,creator=1)
question138= DBInterace.s_CreateQuestion(text=u'What does CAT stand for in a CAT scan?',difficulty=2,theme=8,creator=1)
question139= DBInterace.s_CreateQuestion(text=u'What does Cytology study?',difficulty=2,theme=8,creator=1)
question140= DBInterace.s_CreateQuestion(text=u'What does DVD stand for?',difficulty=2,theme=8,creator=1)
question141= DBInterace.s_CreateQuestion(text=u'What does MG in the car brand stand for?',difficulty=2,theme=8,creator=1)
question142= DBInterace.s_CreateQuestion(text=u'What does VTOL mean when applied to an aircraft?',difficulty=2,theme=8,creator=1)
question143= DBInterace.s_CreateQuestion(text=u'What in radio is FM?',difficulty=2,theme=8,creator=1)
question144= DBInterace.s_CreateQuestion(text=u'What is -459.7F also know as?',difficulty=2,theme=8,creator=1)
question145= DBInterace.s_CreateQuestion(text=u'What is 0 Fahrenheit in centigrade?',difficulty=2,theme=8,creator=1)
question146= DBInterace.s_CreateQuestion(text=u'What is a camel\'s hump made of? Water, fat or muscle?',difficulty=2,theme=8,creator=1)
question147= DBInterace.s_CreateQuestion(text=u'What is a rhinoceros\' horn made of?',difficulty=2,theme=8,creator=1)
question148= DBInterace.s_CreateQuestion(text=u'What is an eolic power station?',difficulty=2,theme=8,creator=1)
question149= DBInterace.s_CreateQuestion(text=u'What is an Ishihara test used for?',difficulty=2,theme=8,creator=1)
question150= DBInterace.s_CreateQuestion(text=u'What is calcium carbonate normally known as?',difficulty=2,theme=8,creator=1)
question151= DBInterace.s_CreateQuestion(text=u'What is measured in Amperes?',difficulty=2,theme=8,creator=1)
question152= DBInterace.s_CreateQuestion(text=u'What is panophobia or pantophobia?',difficulty=2,theme=8,creator=1)
question153= DBInterace.s_CreateQuestion(text=u'What is the fundamental difference between an autogyro and a helicopter?',difficulty=2,theme=8,creator=1)
question154= DBInterace.s_CreateQuestion(text=u'What is the more common name for Ethylene Glycol?',difficulty=2,theme=8,creator=1)
question155= DBInterace.s_CreateQuestion(text=u'What is the more common name of Ascorbic Acid?',difficulty=2,theme=8,creator=1)
question156= DBInterace.s_CreateQuestion(text=u'Which are the only venomous mammals in the world?',difficulty=2,theme=8,creator=1)
question157= DBInterace.s_CreateQuestion(text=u'What lies between Mars and Jupiter?',difficulty=2,theme=8,creator=1)
question158= DBInterace.s_CreateQuestion(text=u'What was the first man-made object to move faster than the speed of sound?',difficulty=2,theme=8,creator=1)
question159= DBInterace.s_CreateQuestion(text=u'What was the gin in the cotton gin invented by Eli Whitney in the US in 1793?',difficulty=2,theme=8,creator=1)
question160= DBInterace.s_CreateQuestion(text=u'What would a Conchologist be interested in?',difficulty=2,theme=8,creator=1)
question161= DBInterace.s_CreateQuestion(text=u'Where, in a household, would you find a magnetron?',difficulty=2,theme=8,creator=1)
question162= DBInterace.s_CreateQuestion(text=u'Which common animal is properly known as Mus Musculus?',difficulty=2,theme=8,creator=1)
question163= DBInterace.s_CreateQuestion(text=u'Which computer operating system has a penguin as its logo?',difficulty=2,theme=8,creator=1)
question164= DBInterace.s_CreateQuestion(text=u'Which crop is attacked by the boll weevil?',difficulty=2,theme=8,creator=1)
question165= DBInterace.s_CreateQuestion(text=u'Which element has atomic number 2?',difficulty=2,theme=8,creator=1)
question166= DBInterace.s_CreateQuestion(text=u'Which German architect who designed the Seagram Building in New York said "Less is more, God is in the details"?',difficulty=2,theme=8,creator=1)
question167= DBInterace.s_CreateQuestion(text=u'Which hangs from the ceiling, a stalactite or a stalagmite?',difficulty=2,theme=8,creator=1)
question168= DBInterace.s_CreateQuestion(text=u'Which is the densest planet in our solar system?',difficulty=2,theme=8,creator=1)
question169= DBInterace.s_CreateQuestion(text=u'Which is the first chemical element in alphabetical order?',difficulty=2,theme=8,creator=1)
question170= DBInterace.s_CreateQuestion(text=u'Which is the largest organ in the human body?',difficulty=2,theme=8,creator=1)
question171= DBInterace.s_CreateQuestion(text=u'Which is the last chemical element (in alphabetical order)?',difficulty=2,theme=8,creator=1)
question172= DBInterace.s_CreateQuestion(text=u'Which is the main component of Brass and Bronze?',difficulty=2,theme=8,creator=1)
question173= DBInterace.s_CreateQuestion(text=u'Which is the opposite point to the Zenith?',difficulty=2,theme=8,creator=1)
question174= DBInterace.s_CreateQuestion(text=u'Which metal do you get from bauxite?',difficulty=2,theme=8,creator=1)
question175= DBInterace.s_CreateQuestion(text=u'Which metal do you get out of Hematite?',difficulty=2,theme=8,creator=1)
question176= DBInterace.s_CreateQuestion(text=u'Which Nobel Prize is awarded by the Caroline Institute of Stockholm?',difficulty=2,theme=8,creator=1)
question177= DBInterace.s_CreateQuestion(text=u'Which period came after the Triassic?',difficulty=2,theme=8,creator=1)
question178= DBInterace.s_CreateQuestion(text=u'Which unit of measurement was defined by Henry III of England by placing three barleycorns in a line?',difficulty=2,theme=8,creator=1)
question179= DBInterace.s_CreateQuestion(text=u'Which vitamin is thiamine?',difficulty=2,theme=8,creator=1)
question180= DBInterace.s_CreateQuestion(text=u'Which was the first jet airliner to enter commercial service?',difficulty=2,theme=8,creator=1)
question181= DBInterace.s_CreateQuestion(text=u'What two time Nobel prize winner was a proponent of Vitamin C?',difficulty=2,theme=8,creator=1)
question182= DBInterace.s_CreateQuestion(text=u'Who invented the centigrade scale?',difficulty=2,theme=8,creator=1)
question183= DBInterace.s_CreateQuestion(text=u'Who was the scientist who measured, on his honeymoon, the amount of heat produced by a local waterfall? (He never had children).',difficulty=2,theme=8,creator=1)
question184= DBInterace.s_CreateQuestion(text=u'Which chemical element gets it\'s name from a greek word meaning \'stranger\'?',difficulty=2,theme=8,creator=1)
question185= DBInterace.s_CreateQuestion(text=u'Which two planets do not have moons?',difficulty=2,theme=8,creator=1)
question186= DBInterace.s_CreateQuestion(text=u'Who won the 1954 Nobel Prize for Chemistry and the 1962 Nobel Peace Prize?',difficulty=2,theme=8,creator=1)
question187= DBInterace.s_CreateQuestion(text=u'Is the sun denser than water?',difficulty=2,theme=8,creator=1)
question188= DBInterace.s_CreateQuestion(text=u'What\'s the difference between a venom and a poison?',difficulty=2,theme=8,creator=1)
question189= DBInterace.s_CreateQuestion(text=u'What is myrrh?',difficulty=2,theme=8,creator=1)
question190= DBInterace.s_CreateQuestion(text=u'In radio and television, among other things, what does UHF stand for?',difficulty=2,theme=8,creator=1)
question191= DBInterace.s_CreateQuestion(text=u'Which sugar makes up nearly 8% of milk and is also known as\'milk sugar\'?',difficulty=2,theme=8,creator=1)
question192= DBInterace.s_CreateQuestion(text=u'What are Lyrids, Perseids, and Leonids?',difficulty=2,theme=8,creator=1)
question193= DBInterace.s_CreateQuestion(text=u'Where in the human body do you find aqueous humour?',difficulty=2,theme=8,creator=1)
question194= DBInterace.s_CreateQuestion(text=u'During which phase of the moon can a solar eclipse occur?',difficulty=2,theme=8,creator=1)
question195= DBInterace.s_CreateQuestion(text=u'What is the name given to rain with a particularly low pH?',difficulty=2,theme=8,creator=1)
question196= DBInterace.s_CreateQuestion(text=u'Which part of the body does an orthopaedic surgeon treat?',difficulty=2,theme=8,creator=1)
question197= DBInterace.s_CreateQuestion(text=u'What\'s the common name of the animal know as\'Vulpes Vulpes\'?',difficulty=2,theme=8,creator=1)
question198= DBInterace.s_CreateQuestion(text=u'Which element, used in electric light filaments and in aviation, has the highest melting point?',difficulty=2,theme=8,creator=1)
question199= DBInterace.s_CreateQuestion(text=u'Which is the largest fish?',difficulty=2,theme=8,creator=1)
question200= DBInterace.s_CreateQuestion(text=u'Besides humans, which are the only primates that live freely in Europe?',difficulty=2,theme=8,creator=1)
question201= DBInterace.s_CreateQuestion(text=u'Hydrated magnesium silicate is found in most bathrooms. By what name is it better known?',difficulty=2,theme=8,creator=1)
question202= DBInterace.s_CreateQuestion(text=u'What (very) common item measures 210 mm by 297 mm by approximately 0.5 mm and weighs about 5g?',difficulty=2,theme=8,creator=1)
question203= DBInterace.s_CreateQuestion(text=u'The ABO grouping classifies what?',difficulty=2,theme=8,creator=1)
question204= DBInterace.s_CreateQuestion(text=u'Parkesine and Bakelite were two early examples of what?',difficulty=2,theme=8,creator=1)
question205= DBInterace.s_CreateQuestion(text=u'Blu-ray discs are set to take over from DVDs. Where does the name come from?',difficulty=2,theme=8,creator=1)
question206= DBInterace.s_CreateQuestion(text=u'What is an explosive mixture of sulphur, charcoal, and saltpetre (potassium nitrate) more commonly known as?',difficulty=2,theme=8,creator=1)
question207= DBInterace.s_CreateQuestion(text=u'The first nuclear powered ship was designed for what purpose?',difficulty=2,theme=8,creator=1)
question208= DBInterace.s_CreateQuestion(text=u'The bark of the Cinchona, historically known as Jesuit\'s Bark or Peruvian Bark, was the original source of which drug?',difficulty=2,theme=8,creator=1)
question209= DBInterace.s_CreateQuestion(text=u'Which metal is named after Cyprus where it was mined in the Roman era?',difficulty=2,theme=8,creator=1)
question210= DBInterace.s_CreateQuestion(text=u'What\'s the name of the type of self-contained cable railway in which a cable attached to a pair of tram-like vehicles on rails moves them up and down a very steep slope, the ascending and descending vehicles counterbalancing each other?',difficulty=2,theme=8,creator=1)
question211= DBInterace.s_CreateQuestion(text=u'What is the laryngeal prominence formed by the angle of the thyroid cartilage surrounding the larynx commonly called?',difficulty=2,theme=8,creator=1)
question212= DBInterace.s_CreateQuestion(text=u'Which Admiral has a wind speed scale named after him?',difficulty=2,theme=8,creator=1)
question213= DBInterace.s_CreateQuestion(text=u'The word\'Galaxy\'comes from the Greek word for what?',difficulty=2,theme=8,creator=1)
question214= DBInterace.s_CreateQuestion(text=u'Alligators are native to only which two countries?',difficulty=2,theme=8,creator=1)
question215= DBInterace.s_CreateQuestion(text=u'Hansen\'s Disease was traditionally known as what?',difficulty=2,theme=8,creator=1)
question216= DBInterace.s_CreateQuestion(text=u'What\'s the name of the fruit originally called Yang Tao in Southwest China, where it originates?',difficulty=2,theme=8,creator=1)
question217= DBInterace.s_CreateQuestion(text=u'What can be categorised as Flip, Bar, Slide, Swivel, or Brick?',difficulty=2,theme=8,creator=1)
question218= DBInterace.s_CreateQuestion(text=u'Which is the largest gland in the human body?',difficulty=2,theme=8,creator=1)
question219= DBInterace.s_CreateQuestion(text=u'How many carats in pure gold?',difficulty=2,theme=8,creator=1)
question220= DBInterace.s_CreateQuestion(text=u'What is decompression sickness commonly known as?',difficulty=2,theme=8,creator=1)
question221= DBInterace.s_CreateQuestion(text=u'What type of fruit is a McIntosh?',difficulty=2,theme=8,creator=1)
question222= DBInterace.s_CreateQuestion(text=u'What is the negatively charged electrode called? (one in which the current flows out)',difficulty=2,theme=8,creator=1)
question223= DBInterace.s_CreateQuestion(text=u'Where or what does the internet domain .cat represent?',difficulty=2,theme=8,creator=1)
question224= DBInterace.s_CreateQuestion(text=u'What does IBM stand for?',difficulty=2,theme=8,creator=1)
question225= DBInterace.s_CreateQuestion(text=u'Which small egg-shaped computer, released in 1996, had only three buttons (A, B, and C) to\'feed\'it,\'clean\'it and play games?',difficulty=2,theme=8,creator=1)
question226= DBInterace.s_CreateQuestion(text=u'What was the name of the first cloned mammal?',difficulty=2,theme=8,creator=1)
question227= DBInterace.s_CreateQuestion(text=u'Who was known as the\'The Wizard of Menlo Park\'and said,\'Genius is one percent inspiration, ninety-nine percent perspiration.\'?',difficulty=2,theme=8,creator=1)
question228= DBInterace.s_CreateQuestion(text=u'A radioactive isotope of Americium can be found in many homes and workplaces. Where?',difficulty=2,theme=8,creator=1)
question229= DBInterace.s_CreateQuestion(text=u' He had to rewrite large parts of it the following year?Who wrote\'The Road Ahead\' about the future of personal computing in 1995 and got it so wrong',difficulty=2,theme=8,creator=1)
question230= DBInterace.s_CreateQuestion(text=u'Which planet has the Great Red Spot in its atmosphere?',difficulty=2,theme=8,creator=1)
question231= DBInterace.s_CreateQuestion(text=u'What is the SI unit of electrical current?',difficulty=2,theme=8,creator=1)
question232= DBInterace.s_CreateQuestion(text=u'The nearest spiral galaxy to this quiz is named Messier 31, M31, or NGC 224, but is more commonly called what?',difficulty=2,theme=8,creator=1)
question233= DBInterace.s_CreateQuestion(text=u'What is the SETI programme?',difficulty=2,theme=8,creator=1)
question234= DBInterace.s_CreateQuestion(text=u'What is the nominal output voltage of an alkaline AA battery?',difficulty=2,theme=8,creator=1)
question235= DBInterace.s_CreateQuestion(text=u'What is the main gas (by volume) in car exhaust?',difficulty=2,theme=8,creator=1)
question236= DBInterace.s_CreateQuestion(text=u'In which animal species does the male get pregnant?',difficulty=2,theme=8,creator=1)
question237= DBInterace.s_CreateQuestion(text=u'What can be classified (using the Hertzsprung-Russell diagram) as white dwarfs, main sequence, subgiants, giants, bright giants, supergiants?',difficulty=2,theme=8,creator=1)
question238= DBInterace.s_CreateQuestion(text=u'What is the name given to nitro-glycerine after it has been mixed with sawdust or clay (diatomaceous earth) to stabilise it?',difficulty=2,theme=8,creator=1)
question239= DBInterace.s_CreateQuestion(text=u'Riboflavin, Niacin, and Folic Acid are examples of what?',difficulty=2,theme=8,creator=1)
question240= DBInterace.s_CreateQuestion(text=u'Which planet in our Solar System has a day that is just over 17 hours long, yet the 98 tilt of it axis means that the poles have sunlight for 42 earth years followed by 42 years of darkness. It has 13 rings and 27 moons.',difficulty=2,theme=8,creator=1)
question241= DBInterace.s_CreateQuestion(text=u'The elements Palladium, Cerium, Uranium, Neptunium, Plutonium are all named after what?',difficulty=2,theme=8,creator=1)
question242= DBInterace.s_CreateQuestion(text=u'How many points or sides does a snowflake have?',difficulty=2,theme=8,creator=1)
question243= DBInterace.s_CreateQuestion(text=u'Which is the lightest gas?',difficulty=2,theme=8,creator=1)
question244= DBInterace.s_CreateQuestion(text=u'What is thanatosis?',difficulty=2,theme=8,creator=1)
question245= DBInterace.s_CreateQuestion(text=u'If your Wassermann test came up positive, what would you be suffering from?',difficulty=2,theme=8,creator=1)
question246= DBInterace.s_CreateQuestion(text=u'Which element takes its name from the Greek for\'pale green\'?',difficulty=2,theme=8,creator=1)
question247= DBInterace.s_CreateQuestion(text=u'What is the name of the oil (or fat) obtained from wool?',difficulty=2,theme=8,creator=1)
question248= DBInterace.s_CreateQuestion(text=u'Where would you find the mound of Venus?',difficulty=2,theme=8,creator=1)
question249= DBInterace.s_CreateQuestion(text=u'What sort of animal is a Rhodesian ridgeback?',difficulty=2,theme=8,creator=1)
question250= DBInterace.s_CreateQuestion(text=u'From which well-known type of flower are Vanilla pods obtained?',difficulty=2,theme=8,creator=1)
question251= DBInterace.s_CreateQuestion(text=u'Anteaters prefer what to ants?',difficulty=2,theme=8,creator=1)
question252= DBInterace.s_CreateQuestion(text=u'Which is the only insect that can turn its head to look directly behind itself?',difficulty=2,theme=8,creator=1)
question253= DBInterace.s_CreateQuestion(text=u'What sort of substances are adrenaline, cortisone, insulin, and oestrogens?',difficulty=2,theme=8,creator=1)
question254= DBInterace.s_CreateQuestion(text=u'What is inflamed when you suffer from nephritis?',difficulty=2,theme=8,creator=1)
question255= DBInterace.s_CreateQuestion(text=u'How many noble gases are there?',difficulty=2,theme=8,creator=1)
question256= DBInterace.s_CreateQuestion(text=u'Pencil lead is made out what?',difficulty=2,theme=8,creator=1)
question257= DBInterace.s_CreateQuestion(text=u'What did Foucault\'s pendulum prove?',difficulty=2,theme=8,creator=1)
question258= DBInterace.s_CreateQuestion(text=u'There are three types of nuclear radiation. What are they called?',difficulty=2,theme=8,creator=1)
question259= DBInterace.s_CreateQuestion(text=u'Freud published his most influential book in 1900. What was it called?',difficulty=2,theme=8,creator=1)
question260= DBInterace.s_CreateQuestion(text=u'For fans of Mad magazine: what is an axolotl?',difficulty=2,theme=8,creator=1)
question261= DBInterace.s_CreateQuestion(text=u'What is the antimatter equivalent of the electron?',difficulty=2,theme=8,creator=1)
question262= DBInterace.s_CreateQuestion(text=u'What are Sodium Thiopental, Pancuronium Bromide, and Potassium Chloride taken in that order?',difficulty=2,theme=8,creator=1)
question263= DBInterace.s_CreateQuestion(text=u'What kind of animal is a blue-fronted parrot?',difficulty=2,theme=8,creator=1)
question264= DBInterace.s_CreateQuestion(text=u'What is the name of the alloy made of 95% aluminium, 4% copper and small amounts of magnesium and manganese?',difficulty=2,theme=8,creator=1)
question265= DBInterace.s_CreateQuestion(text=u'Who wrote the book\'The Double Helix: A Personal Account of the Discovery of the Structure of DNA\'?',difficulty=2,theme=8,creator=1)
question266= DBInterace.s_CreateQuestion(text=u'Who invented natural logarithms?',difficulty=2,theme=8,creator=1)
question267= DBInterace.s_CreateQuestion(text=u'Which is the main protein in milk?',difficulty=2,theme=8,creator=1)
question268= DBInterace.s_CreateQuestion(text=u'What part of the body is affected by Otitis?',difficulty=2,theme=8,creator=1)
question269= DBInterace.s_CreateQuestion(text=u'Which branch of physics deals with sound?',difficulty=2,theme=8,creator=1)
question270= DBInterace.s_CreateQuestion(text=u'Which law states that, at a constant temperature, the pressure of a gas is inversely proportional to its volume?',difficulty=2,theme=8,creator=1)
question271= DBInterace.s_CreateQuestion(text=u'Which element has the chemical symbol Rf?',difficulty=2,theme=8,creator=1)
question272= DBInterace.s_CreateQuestion(text=u'Which temperature has the same value in Fahrenheit and Celsius?',difficulty=2,theme=8,creator=1)
question273= DBInterace.s_CreateQuestion(text=u'In which organ would you find the pineal gland?',difficulty=2,theme=8,creator=1)
question274= DBInterace.s_CreateQuestion(text=u'Aquaculture is the correct term for what?',difficulty=2,theme=8,creator=1)
question275= DBInterace.s_CreateQuestion(text=u'What kind of animal is a basilisk?',difficulty=2,theme=8,creator=1)
question276= DBInterace.s_CreateQuestion(text=u'Which is the tenth largest body orbiting the sun?',difficulty=2,theme=8,creator=1)


answer1 =DBInterace.s_CreateAnswer(1,"Trafalgar Square")
answer2 =DBInterace.s_CreateAnswer(2,"Norwegian")
answer3 =DBInterace.s_CreateAnswer(3,"Malaga")
answer4 =DBInterace.s_CreateAnswer(4,"Frans Hals")
answer5 =DBInterace.s_CreateAnswer(5,"J M W Turner")
answer6 =DBInterace.s_CreateAnswer(6,"Whistler\'s Mother")
answer7 =DBInterace.s_CreateAnswer(7,"Sunflowers")
answer8 =DBInterace.s_CreateAnswer(8,"Horses")
answer9 =DBInterace.s_CreateAnswer(9,"Antony Gormley")
answer10 =DBInterace.s_CreateAnswer(10,"Anne of Cleves")
answer11 =DBInterace.s_CreateAnswer(11,"A drugs raid")
answer12 =DBInterace.s_CreateAnswer(12,"Peter Duncan")
answer13 =DBInterace.s_CreateAnswer(13,"Rachel McAdams")
answer14 =DBInterace.s_CreateAnswer(14,"Peter Andre")
answer15 =DBInterace.s_CreateAnswer(15,"Sweet Dreams")
answer16 =DBInterace.s_CreateAnswer(16,"World War II")
answer17 =DBInterace.s_CreateAnswer(17,"Stone Roses")
answer18 =DBInterace.s_CreateAnswer(18,"Steve Lamacq")
answer19 =DBInterace.s_CreateAnswer(19,"Charlie Slater")
answer20 =DBInterace.s_CreateAnswer(20,"Freddie Fisher")
answer21 =DBInterace.s_CreateAnswer(21,"Leipzig")
answer22 =DBInterace.s_CreateAnswer(22,"170")
answer23 =DBInterace.s_CreateAnswer(23,"Naas")
answer24 =DBInterace.s_CreateAnswer(24,"Rome")
answer25 =DBInterace.s_CreateAnswer(25,"Hungary")
answer26 =DBInterace.s_CreateAnswer(26,"Toledo")
answer27 =DBInterace.s_CreateAnswer(27,"Toulouse")
answer28 =DBInterace.s_CreateAnswer(28,"Baseball")
answer29 =DBInterace.s_CreateAnswer(29,"Albania")
answer30 =DBInterace.s_CreateAnswer(30,"Bremen")
answer31 =DBInterace.s_CreateAnswer(31,"6300")
answer32 =DBInterace.s_CreateAnswer(32,"Unfinished at the time of his death")
answer33 =DBInterace.s_CreateAnswer(33,"Ghana")
answer34 =DBInterace.s_CreateAnswer(34,"1793")
answer35 =DBInterace.s_CreateAnswer(35,"Venice")
answer36 =DBInterace.s_CreateAnswer(36,"1967")
answer37 =DBInterace.s_CreateAnswer(37,"Japan")
answer38 =DBInterace.s_CreateAnswer(38,"Princeton")
answer39 =DBInterace.s_CreateAnswer(39,"Sweden")
answer40 =DBInterace.s_CreateAnswer(40,"Colombia")
answer41 =DBInterace.s_CreateAnswer(41,"Steve Jobs")
answer42 =DBInterace.s_CreateAnswer(42,"Public Broadcasting Service")
answer43 =DBInterace.s_CreateAnswer(43,"Carlisle")
answer44 =DBInterace.s_CreateAnswer(44,"Lille")
answer45 =DBInterace.s_CreateAnswer(45,"Washington")
answer46 =DBInterace.s_CreateAnswer(46,"Toothpaste")
answer47 =DBInterace.s_CreateAnswer(47,"Venice")
answer48 =DBInterace.s_CreateAnswer(48,"The mouse")
answer49 =DBInterace.s_CreateAnswer(49,"A power cut")
answer50 =DBInterace.s_CreateAnswer(50,"Radio Caroline")
answer51 =DBInterace.s_CreateAnswer(51,"Sacriston ")
answer52 =DBInterace.s_CreateAnswer(52,"Warwickshire")
answer53 =DBInterace.s_CreateAnswer(53,"ESPN")
answer54 =DBInterace.s_CreateAnswer(54,"Royal Lytham")
answer55 =DBInterace.s_CreateAnswer(55,"Beijing")
answer56 =DBInterace.s_CreateAnswer(56,"Concorde Agreement")
answer57 =DBInterace.s_CreateAnswer(57,"Mikel Astarloza")
answer58 =DBInterace.s_CreateAnswer(58,"12")
answer59 =DBInterace.s_CreateAnswer(59,"What nationality is Stosur?")
answer60 =DBInterace.s_CreateAnswer(60,"Frankie Dettori")
answer61= DBInterace.s_CreateAnswer(61,u'A variety of Apple')
answer62= DBInterace.s_CreateAnswer(62,u'Kiwi or kiwifruit')
answer63= DBInterace.s_CreateAnswer(63,u'One tonne (or metric ton)')
answer64= DBInterace.s_CreateAnswer(64,u'10,000 (100x100 metres)')
answer65= DBInterace.s_CreateAnswer(65,u'Mars ')
answer66= DBInterace.s_CreateAnswer(66,u'The killer whale ')
answer67= DBInterace.s_CreateAnswer(67,u'Uranus')
answer68= DBInterace.s_CreateAnswer(68,u'The Kelvin (not degree Kelvin)')
answer69= DBInterace.s_CreateAnswer(69,u'Fungus')
answer70= DBInterace.s_CreateAnswer(70,u'Corundum')
answer71= DBInterace.s_CreateAnswer(71,u'Living together of unlike organisms')
answer72= DBInterace.s_CreateAnswer(72,u'Yuri Gagarin')
answer73= DBInterace.s_CreateAnswer(73,u'Isobath ')
answer74= DBInterace.s_CreateAnswer(74,u'Amember of the weasel family')
answer75= DBInterace.s_CreateAnswer(75,u'Hertz')
answer76= DBInterace.s_CreateAnswer(76,u'Pixel')
answer77= DBInterace.s_CreateAnswer(77,u'On a beach')
answer78= DBInterace.s_CreateAnswer(78,u'Carbon monoxide')
answer79= DBInterace.s_CreateAnswer(79,u'Flyer')
answer80= DBInterace.s_CreateAnswer(80,u'Plate Tectonics')
answer81= DBInterace.s_CreateAnswer(81,u'Carbon')
answer82= DBInterace.s_CreateAnswer(82,u'Migraine')
answer83= DBInterace.s_CreateAnswer(83,u'Carbon 14')
answer84= DBInterace.s_CreateAnswer(84,u'Yes (but no weight)')
answer85= DBInterace.s_CreateAnswer(85,u'Tooth enamel')
answer86= DBInterace.s_CreateAnswer(86,u'Black')
answer87= DBInterace.s_CreateAnswer(87,u'The World Wide Web at CERN in Geneva')
answer88= DBInterace.s_CreateAnswer(88,u'Water')
answer89= DBInterace.s_CreateAnswer(89,u'Pitch and yaw')
answer90= DBInterace.s_CreateAnswer(90,u'Perth and Sydney')
answer91= DBInterace.s_CreateAnswer(91,u'A bullet train')
answer92= DBInterace.s_CreateAnswer(92,u'An auto-rickshaw')
answer93= DBInterace.s_CreateAnswer(93,u'Newton')
answer94= DBInterace.s_CreateAnswer(94,u'The stratosphere')
answer95= DBInterace.s_CreateAnswer(95,u'Great circle')
answer96= DBInterace.s_CreateAnswer(96,u'The Mini')
answer97= DBInterace.s_CreateAnswer(97,u'Saturn V ')
answer98= DBInterace.s_CreateAnswer(98,u'Amplitude Modulation')
answer99= DBInterace.s_CreateAnswer(99,u'Red, green and blue')
answer100= DBInterace.s_CreateAnswer(100,u'Dry ice')
answer101= DBInterace.s_CreateAnswer(101,u'Dodo')
answer102= DBInterace.s_CreateAnswer(102,u'30 degrees')
answer103= DBInterace.s_CreateAnswer(103,u'O3')
answer104= DBInterace.s_CreateAnswer(104,u'The Spirit of Ecstacy')
answer105= DBInterace.s_CreateAnswer(105,u'Hologram')
answer106= DBInterace.s_CreateAnswer(106,u'Whales')
answer107= DBInterace.s_CreateAnswer(107,u'Sails')
answer108= DBInterace.s_CreateAnswer(108,u'Raising water')
answer109= DBInterace.s_CreateAnswer(109,u'Refraction')
answer110= DBInterace.s_CreateAnswer(110,u'Directly beneath it')
answer111= DBInterace.s_CreateAnswer(111,u'The tongue')
answer112= DBInterace.s_CreateAnswer(112,u'Mars')
answer113= DBInterace.s_CreateAnswer(113,u'Galileo Galilei')
answer114= DBInterace.s_CreateAnswer(114,u'A double helix')
answer115= DBInterace.s_CreateAnswer(115,u'Computer languages')
answer116= DBInterace.s_CreateAnswer(116,u'Yahoo')
answer117= DBInterace.s_CreateAnswer(117,u'Your stomach making noises')
answer118= DBInterace.s_CreateAnswer(118,u'Sublimation')
answer119= DBInterace.s_CreateAnswer(119,u'Two')
answer120= DBInterace.s_CreateAnswer(120,u'One')
answer121= DBInterace.s_CreateAnswer(121,u'A nibble')
answer122= DBInterace.s_CreateAnswer(122,u'Single lens reflex')
answer123= DBInterace.s_CreateAnswer(123,u'North Carolina')
answer124= DBInterace.s_CreateAnswer(124,u'Red')
answer125= DBInterace.s_CreateAnswer(125,u'Compact Disk Read Only Memory')
answer126= DBInterace.s_CreateAnswer(126,u'The Granny Smith apple')
answer127= DBInterace.s_CreateAnswer(127,u'Diamond')
answer128= DBInterace.s_CreateAnswer(128,u'Asymmetric Digital Subscriber Line')
answer129= DBInterace.s_CreateAnswer(129,u'Peta')
answer130= DBInterace.s_CreateAnswer(130,u'Equinox')
answer131= DBInterace.s_CreateAnswer(131,u'calendar year?')
answer132= DBInterace.s_CreateAnswer(132,u'Quarks')
answer133= DBInterace.s_CreateAnswer(133,u'Dromedary and Bactrian')
answer134= DBInterace.s_CreateAnswer(134,u'It\'s a white odourless crystalline powder')
answer135= DBInterace.s_CreateAnswer(135,u'Orange')
answer136= DBInterace.s_CreateAnswer(136,u'The Photoelectric effect')
answer137= DBInterace.s_CreateAnswer(137,u'Television')
answer138= DBInterace.s_CreateAnswer(138,u'Computerised Axial Tomography')
answer139= DBInterace.s_CreateAnswer(139,u'Structure, function and life of cells')
answer140= DBInterace.s_CreateAnswer(140,u'Digital Versatile Disc')
answer141= DBInterace.s_CreateAnswer(141,u'Morris Garages')
answer142= DBInterace.s_CreateAnswer(142,u'Vertical Take Off and Landing')
answer143= DBInterace.s_CreateAnswer(143,u'Frequency modulation')
answer144= DBInterace.s_CreateAnswer(144,u'Absolute zero')
answer145= DBInterace.s_CreateAnswer(145,u'-18 degrees')
answer146= DBInterace.s_CreateAnswer(146,u'Fat')
answer147= DBInterace.s_CreateAnswer(147,u'Hair')
answer148= DBInterace.s_CreateAnswer(148,u'Wind powered')
answer149= DBInterace.s_CreateAnswer(149,u'To test for colour blindness')
answer150= DBInterace.s_CreateAnswer(150,u'Chalk')
answer151= DBInterace.s_CreateAnswer(151,u'Electric current')
answer152= DBInterace.s_CreateAnswer(152,u'Fear of everything')
answer153= DBInterace.s_CreateAnswer(153,u'A helicopter has powered rotors')
answer154= DBInterace.s_CreateAnswer(154,u'Antifreeze')
answer155= DBInterace.s_CreateAnswer(155,u'Vitamin C')
answer156= DBInterace.s_CreateAnswer(156,u'The duckbill platypus, some shrews and the solenodon')
answer157= DBInterace.s_CreateAnswer(157,u'The Asteroid Belt')
answer158= DBInterace.s_CreateAnswer(158,u'A whip')
answer159= DBInterace.s_CreateAnswer(159,u'Engine')
answer160= DBInterace.s_CreateAnswer(160,u'Shells')
answer161= DBInterace.s_CreateAnswer(161,u'In a microwave oven')
answer162= DBInterace.s_CreateAnswer(162,u'Mouse')
answer163= DBInterace.s_CreateAnswer(163,u'Linux')
answer164= DBInterace.s_CreateAnswer(164,u'Cotton')
answer165= DBInterace.s_CreateAnswer(165,u'Helium')
answer166= DBInterace.s_CreateAnswer(166,u'Ludwig Mies van Der Rohe')
answer167= DBInterace.s_CreateAnswer(167,u'Stalactite')
answer168= DBInterace.s_CreateAnswer(168,u'The Earth')
answer169= DBInterace.s_CreateAnswer(169,u'Actinium (atomic number 89)')
answer170= DBInterace.s_CreateAnswer(170,u'The skin')
answer171= DBInterace.s_CreateAnswer(171,u'Zirconium (atomic number 40)')
answer172= DBInterace.s_CreateAnswer(172,u'Copper')
answer173= DBInterace.s_CreateAnswer(173,u'Nadir')
answer174= DBInterace.s_CreateAnswer(174,u'Aluminium')
answer175= DBInterace.s_CreateAnswer(175,u'Iron')
answer176= DBInterace.s_CreateAnswer(176,u'Physiology and Medicine')
answer177= DBInterace.s_CreateAnswer(177,u'Jurassic')
answer178= DBInterace.s_CreateAnswer(178,u'An inch')
answer179= DBInterace.s_CreateAnswer(179,u'Vitamin B1')
answer180= DBInterace.s_CreateAnswer(180,u'The DH Comet')
answer181= DBInterace.s_CreateAnswer(181,u'Linus Pauling')
answer182= DBInterace.s_CreateAnswer(182,u'Anders Celsius')
answer183= DBInterace.s_CreateAnswer(183,u'James Prescott Joule')
answer184= DBInterace.s_CreateAnswer(184,u'Xenon')
answer185= DBInterace.s_CreateAnswer(185,u'Mercury and Venus')
answer186= DBInterace.s_CreateAnswer(186,u'Linus Pauling')
answer187= DBInterace.s_CreateAnswer(187,u'Yes, 1.41 times as dense')
answer188= DBInterace.s_CreateAnswer(188,u'A venom is injected by biting or stinging')
answer189= DBInterace.s_CreateAnswer(189,u'A resin. Commiphora myrrha.')
answer190= DBInterace.s_CreateAnswer(190,u'Ultra High Frequency')
answer191= DBInterace.s_CreateAnswer(191,u'Lactose')
answer192= DBInterace.s_CreateAnswer(192,u'Meteor showers')
answer193= DBInterace.s_CreateAnswer(193,u'Eye')
answer194= DBInterace.s_CreateAnswer(194,u'New moon')
answer195= DBInterace.s_CreateAnswer(195,u'Acid rain')
answer196= DBInterace.s_CreateAnswer(196,u'The musculoskeletal system')
answer197= DBInterace.s_CreateAnswer(197,u'Fox')
answer198= DBInterace.s_CreateAnswer(198,u'Tungsten at 3,683K (3,410 C), Carbon doesn\'t melt under normal pressure, it sublimes')
answer199= DBInterace.s_CreateAnswer(199,u'Whale shark')
answer200= DBInterace.s_CreateAnswer(200,u'Barbary Macaques in Gibraltar')
answer201= DBInterace.s_CreateAnswer(201,u'Talc or talcum powder')
answer202= DBInterace.s_CreateAnswer(202,u'A sheet of A4 paper (80g/m2)')
answer203= DBInterace.s_CreateAnswer(203,u'Blood groups')
answer204= DBInterace.s_CreateAnswer(204,u'Synthetic plastic')
answer205= DBInterace.s_CreateAnswer(205,u'It uses a blue laser instead of red')
answer206= DBInterace.s_CreateAnswer(206,u'Gunpowder')
answer207= DBInterace.s_CreateAnswer(207,u'Icebreaking (NS Lenin in 1959)')
answer208= DBInterace.s_CreateAnswer(208,u'Quinine')
answer209= DBInterace.s_CreateAnswer(209,u'Copper')
answer210= DBInterace.s_CreateAnswer(210,u'Funicular')
answer211= DBInterace.s_CreateAnswer(211,u'Adam\'s Apple')
answer212= DBInterace.s_CreateAnswer(212,u'Sir Francis Beaufort')
answer213= DBInterace.s_CreateAnswer(213,u'Milk')
answer214= DBInterace.s_CreateAnswer(214,u'USA and China')
answer215= DBInterace.s_CreateAnswer(215,u'Leprosy')
answer216= DBInterace.s_CreateAnswer(216,u'Kiwi or kiwifruit')
answer217= DBInterace.s_CreateAnswer(217,u'Mobile phones')
answer218= DBInterace.s_CreateAnswer(218,u'Liver')
answer219= DBInterace.s_CreateAnswer(219,u'24')
answer220= DBInterace.s_CreateAnswer(220,u'The bends')
answer221= DBInterace.s_CreateAnswer(221,u'An apple')
answer222= DBInterace.s_CreateAnswer(222,u'Cathode')
answer223= DBInterace.s_CreateAnswer(223,u'The Catalan-speaking community')
answer224= DBInterace.s_CreateAnswer(224,u'International Business Machines')
answer225= DBInterace.s_CreateAnswer(225,u'Tamagotchi')
answer226= DBInterace.s_CreateAnswer(226,u'Dolly the sheep in 1997')
answer227= DBInterace.s_CreateAnswer(227,u'Thomas Edison')
answer228= DBInterace.s_CreateAnswer(228,u'Smoke detectors')
answer229= DBInterace.s_CreateAnswer(229,u'Bill Gates')
answer230= DBInterace.s_CreateAnswer(230,u'Jupiter')
answer231= DBInterace.s_CreateAnswer(231,u'Ampere')
answer232= DBInterace.s_CreateAnswer(232,u'Andromeda Galaxy')
answer233= DBInterace.s_CreateAnswer(233,u'The Search for Extra Terrestrial Intelligence')
answer234= DBInterace.s_CreateAnswer(234,u'1.5 volts')
answer235= DBInterace.s_CreateAnswer(235,u'Nitrogen (N2)')
answer236= DBInterace.s_CreateAnswer(236,u'Sea horses')
answer237= DBInterace.s_CreateAnswer(237,u'Stars')
answer238= DBInterace.s_CreateAnswer(238,u'Dynamite')
answer239= DBInterace.s_CreateAnswer(239,u'Vitamins (B2, B3, and B9)')
answer240= DBInterace.s_CreateAnswer(240,u'Uranus')
answer241= DBInterace.s_CreateAnswer(241,u'Planets (and asteroids, considered planets at the time)')
answer242= DBInterace.s_CreateAnswer(242,u'Six')
answer243= DBInterace.s_CreateAnswer(243,u'Hydrogen')
answer244= DBInterace.s_CreateAnswer(244,u'Playing dead (playing possum)')
answer245= DBInterace.s_CreateAnswer(245,u'Syphyllis')
answer246= DBInterace.s_CreateAnswer(246,u'Chlorine')
answer247= DBInterace.s_CreateAnswer(247,u'Lanolin (adeps lanae)')
answer248= DBInterace.s_CreateAnswer(248,u'In the palm of your hand or just above the genitals')
answer249= DBInterace.s_CreateAnswer(249,u'A dog')
answer250= DBInterace.s_CreateAnswer(250,u'Orchids')
answer251= DBInterace.s_CreateAnswer(251,u'Termites')
answer252= DBInterace.s_CreateAnswer(252,u'The praying mantis')
answer253= DBInterace.s_CreateAnswer(253,u'Hormones')
answer254= DBInterace.s_CreateAnswer(254,u'The kidneys')
answer255= DBInterace.s_CreateAnswer(255,u'Six: helium, neon, argon, krypton, xenon, and radon.')
answer256= DBInterace.s_CreateAnswer(256,u'Graphite and clay (mainly)')
answer257= DBInterace.s_CreateAnswer(257,u'That the earth rotates')
answer258= DBInterace.s_CreateAnswer(258,u'Alpha, Beta, and Gamma')
answer259= DBInterace.s_CreateAnswer(259,u'The Interpretation of Dreams')
answer260= DBInterace.s_CreateAnswer(260,u'A salamander')
answer261= DBInterace.s_CreateAnswer(261,u'The positron')
answer262= DBInterace.s_CreateAnswer(262,u'The lethal injection used to execute prisoners in the USA')
answer263= DBInterace.s_CreateAnswer(263,u'A parrot')
answer264= DBInterace.s_CreateAnswer(264,u'Duraluminium (also know as duraluminum, duralumin, or dural)')
answer265= DBInterace.s_CreateAnswer(265,u'James Watson')
answer266= DBInterace.s_CreateAnswer(266,u'John Napier')
answer267= DBInterace.s_CreateAnswer(267,u'Casein')
answer268= DBInterace.s_CreateAnswer(268,u'The ear')
answer269= DBInterace.s_CreateAnswer(269,u'Acoustics')
answer270= DBInterace.s_CreateAnswer(270,u'Boyle\'s Law')
answer271= DBInterace.s_CreateAnswer(271,u'Rutherfordium')
answer272= DBInterace.s_CreateAnswer(272,u'-40')
answer273= DBInterace.s_CreateAnswer(273,u'The brain')
answer274= DBInterace.s_CreateAnswer(274,u'Fish farming')
answer275= DBInterace.s_CreateAnswer(275,u'A lizard')
answer276= DBInterace.s_CreateAnswer(276,u'Pluto (Eris is the ninth)')


DBInterace.CreateSource(id=None,difficulty=1,theme=1,website=u'https://es.coursera.org/learn/dog-emotion-and-cognition')
DBInterace.CreateSource(id=None,difficulty=2,theme=1,website=u'https://es.coursera.org/learn/dog-emotion-and-cognition')
DBInterace.CreateSource(id=None,difficulty=3,theme=1,website=u'https://es.coursera.org/learn/dog-emotion-and-cognition')
DBInterace.CreateSource(id=None,difficulty=1,theme=2,website=u'https://alison.com/course/Google-Earth')
DBInterace.CreateSource(id=None,difficulty=2,theme=2,website=u'https://alison.com/course/Google-Earth')
DBInterace.CreateSource(id=None,difficulty=3,theme=2,website=u'https://alison.com/course/Google-Earth')
DBInterace.CreateSource(id=None,difficulty=1,theme=3,website=u'https://es.coursera.org/learn/animal-behaviour')
DBInterace.CreateSource(id=None,difficulty=2,theme=3,website=u'https://es.coursera.org/learn/animal-behaviour')
DBInterace.CreateSource(id=None,difficulty=3,theme=3,website=u'https://es.coursera.org/learn/animal-behaviour')
DBInterace.CreateSource(id=None,difficulty=1,theme=5,website=u'https://es.coursera.org/learn/art-activity')
DBInterace.CreateSource(id=None,difficulty=2,theme=5,website=u'https://es.coursera.org/learn/art-activity')
DBInterace.CreateSource(id=None,difficulty=3,theme=5,website=u'https://es.coursera.org/learn/art-activity')
DBInterace.CreateSource(difficulty=1,theme=6,website=u'https://es.coursera.org/learn/international-entertainment-sports-marketing')
DBInterace.CreateSource(difficulty=2,theme=6,website=u'https://es.coursera.org/learn/international-entertainment-sports-marketing')
DBInterace.CreateSource(difficulty=3,theme=6,website=u'https://es.coursera.org/learn/international-entertainment-sports-marketing')
DBInterace.CreateSource(difficulty=1,theme=7,website=u'https://es.coursera.org/learn/bighistory')
DBInterace.CreateSource(difficulty=2,theme=7,website=u'https://es.coursera.org/learn/bighistory')
DBInterace.CreateSource(difficulty=3,theme=7,website=u'https://es.coursera.org/learn/bighistory')
DBInterace.CreateSource(difficulty=1,theme=8,website=u'https://es.coursera.org/learn/astronomy-technology')
DBInterace.CreateSource(difficulty=2,theme=8,website=u'https://es.coursera.org/learn/astronomy-technology')
DBInterace.CreateSource(difficulty=3,theme=8,website=u'https://es.coursera.org/learn/astronomy-technology')
DBInterace.CreateSource(difficulty=1,theme=9,website=u'https://www.cursos-academicos.com/Programma-de-coaching-deportivo/Espana/La-Salle-International-Graduate-School-IGS')
DBInterace.CreateSource(difficulty=2,theme=9,website=u'https://www.cursos-academicos.com/Programma-de-coaching-deportivo/Espana/La-Salle-International-Graduate-School-IGS')
DBInterace.CreateSource(difficulty=3,theme=9,website=u'https://www.cursos-academicos.com/Programma-de-coaching-deportivo/Espana/La-Salle-International-Graduate-School-IGS')



knowledge = DBInterace.GetKnowledge(person=1)
print 'Person knowledge :', knowledge

#Let\'s add to user knowledge of Biology at level 'Hard'

#Knowledge is empty, let\'s create it
# Notice, that knowledge with id == 1 is a special type of knownedge, called 'UNKNOWN'
# First - get difficulty for fixed name

difficulty = DBInterace.GetDifficultyByLabel('Hard')
if difficulty is None:
    difficulty = DBInterace.s_CreateDifficulty(difficulty='Hard')
hard_id = difficulty.id
print 'Id of difficulty "Hard" is', hard_id

#Now select theme, that user knows
#Firstly get all themes with appropriate label
themes = DBInterace.GetThemeSequences('Biology')
for sequence in themes:
    print 'New sequence :'
    for name, id in sequence:
        print 'Name :', name, 'ID :', id

# Here we have only one Biology label, let\'s use it
if len(themes) != 1:
    print 'More than one Biology in the database, should be selected on of them'
    exit(0)
biology_sequence = themes[0]
biology_theme_id = biology_sequence[0][1]
print 'Target Biology theme ID :', biology_theme_id
#If there i

is_created_or_exist = DBInterace.AddUserKnowledge(2, hard_id, biology_theme_id)
print 'Knowledge is created or already exists :', is_created_or_exist

# Now let\'s add Biology-Mammals theme to user knowledge
# First' let us get all sequences for "Mammals"
themes = DBInterace.GetThemeSequences('Mammals')
for sequence in themes:
    print 'New sequence :'
    for name, id in sequence:
        print 'Name :', name, 'ID :', id

target_seq = []
#After, for each sequences, we get if user knows everything except last item
for sequence in themes:
    reduced_seq = sequence[1:]
    marker = DBInterace.CheckPersonKnowsSeq(2, reduced_seq)
    print 'User', 'know' if marker else "don't know", 'about', reduced_seq
    # We assuming, that user dont know about Biology and Geography at the same time
    # If he do, them dedision should be made out of context, for example if user pressed "Biology'
    # And want to have estimation for 'Mammals', it should lead us to select sequence
    # For test pruposes, we can assume that all labels in the graph are unique
    if marker:
        target_seq.append(sequence)

if len(target_seq) != 1:
    print 'More than one Mammals in the database, should be selected on of them'
    exit(0)
mammals_sequence = target_seq[0]
mammals_theme_id = mammals_sequence[0][1]
print 'Target Mammals theme ID :', mammals_theme_id

is_created_or_exist = DBInterace.AddUserKnowledge(2, hard_id, mammals_theme_id)
print 'Knowledge is created or already exists :', is_created_or_exist

# Now let\'s assume, that Vasya is asking question about biology-mammals
question_text = u'Is cow a mammal?'
#Firstly let us check if such question exists
matches = [item[0] for item in DBInterace.GetMatchQuestions(question_text)]
for item in matches:
    print 'Matching question is', item.text

# Obviously there is no appropriate questions for that topic
# So we need to add this question into the database
question = DBInterace.s_CreateQuestion(text=question_text, creator=1)

# Let\'s assume, that Vadim is asking for a same question
question_text = u'Is cow a mammal?'
#Firstly let us check if such question exists
matches = [item[0] for item in DBInterace.GetMatchQuestions(question_text)]
for item in matches:
    print 'Matching question is', item.text

# Ok, we have matching question
# Now Vadim may tag it

difficulty = DBInterace.GetDifficultyByLabel('Easy')
if difficulty is None:
    difficulty = DBInterace.s_CreateDifficulty(difficulty='Easy')
easy_id = difficulty.id
print 'Id of difficulty "Easy" is', easy_id

updated = DBInterace.UpdateQuestion(id=question.id, difficulty=easy_id)
print 'Updated :', updated
question = DBInterace.AtomicGetQuestion(question.id)
print 'Question difficulty :', question.difficulty.difficulty

# Now, is Vasya will answer the question

answer_text = 'Yes'
matches = [item[0] for item in DBInterace.GetMatchAnswers(question.id, answer_text)]
for item in matches:
    print 'Matching answer for question', question.text, 'is', item.text

# Obviously we dont have maching answers

answer = DBInterace.s_CreateAnswer(question.id, answer_text)
DBInterace.UpdateAnswer(answer.id, answer.frequency + 1)

# Now frequency is updated for matching answer!
# Try to select again, and you will see

matches = [item[0] for item in DBInterace.GetMatchAnswers(question.id, answer_text)]
for item in matches:
    print 'Matching answer for question', question.text, 'is', item.text


# How long is meter?
text = u'How long is meter?'
list_of_question = DBInterace.GetMatchQuestions(text)

if list_of_question == []:
    #create auestion
    pass
else:
    best_match = list_of_question[0]
    id_of_best_match = best_match.id
    answers = DBInterace.GetAnswer(id=id_of_best_match)
    answers = sorted(answers, key=lambda x : x.frequency, reverse=True)
    best_answer = answers[0]



DBInterace.UpdateAnswer(answer1.id, answer1.frequency + 1)
